package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public abstract class OrderedCriteria implements Criteria
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public OrderedCriteria() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

}